baseURL = "https://danieledapo.github.io"
languageCode = "en-us"

# this title is used only for rss readers which do not agree upon whether to
# interpret them as html text or not.
title = "dapo"

enableEmoji = true

disableKinds = ["taxonomy"]

[markup]
[markup.highlight]
style = "friendly"

[params.author]
name = "Daniele D'Orazio"

[markup.goldmark.renderer]
unsafe = true
