#!/bin/bash

set -eux

if ! command -v pygmentize; then
    echo "Please install pygments with pip install pygments"
    exit 1
fi

hugo

git add .
git commit

git push origin HEAD
git subtree push --prefix public origin master
